apiVersion: v1
kind: Service
metadata:
  name: {{ template "dns-lookup-tool.fullname" . }}
  labels:
    app: {{ template "dns-lookup-tool.name" . }}
    chart: {{ template "dns-lookup-tool.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "dns-lookup-tool.name" . }}
    release: {{ .Release.Name }}
